name: Build C# Project
on:
  push:
    branches: [ main ]
permissions:
  actions: write
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore AdbWrapper.csproj
    - name: Build
      run: dotnet build AdbWrapper.csproj --configuration Release --no-restore
    - name: Publish
      run: dotnet publish AdbWrapper.csproj -c Release -o ./publish --self-contained false
    - name: List publish directory
      run: dir ./publish
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AdbWrapperExe
        path: ./publish/AdbWrapper.exe
        if-no-files-found: error

